name: Docker Build and Push

on:
  push:
    paths:
      - '.ci/Dockerfile'
    branches:
      - master
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: |
          env
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: kitsudo
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        id: docker_build_alpine
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .ci/Dockerfile
          build-args: |
            BUILD=github
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kitsudo/${{ env.REPO_NAME }}:latest
            kitsudo/${{ env.REPO_NAME }}:${{ github.ref_name }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: kitsudo
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: kitsudo/${{ env.REPO_NAME }}
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}
